#!/bin/bash
bold=$(tput bold)
normal=$(tput sgr0)

echo "${bold}[DOWNLOADING]${normal}"
mkdir /tmp/lighttheme
echo "${bold}[Downloading base installer]${normal}"
curl -# https://raw.githubusercontent.com/Weilbyte/PVEDiscordDark/master/serverside/ddRemove.sh > /tmp/lighttheme/ddremove.sh
chmod +x /tmp/lighttheme/ddremove.sh
echo "${bold}[Downloading loose files]${normal}"
curl -# https://raw.githubusercontent.com/Weilbyte/PVEDiscordDark/master/serverside/jsmod/6.0-4/pvemanagerlib.js.original > /tmp/lighttheme/pvemanagerlib.js
curl -# https://raw.githubusercontent.com/Weilbyte/PVEDiscordDark/master/serverside/jsmod/6.0-4/charts.js.original > /tmp/lighttheme/charts.js
curl -# https://raw.githubusercontent.com/Weilbyte/PVEDiscordDark/master/serverside/jsmod/6.0-4/proxmoxlib.js.original > /tmp/lighttheme/proxmoxlib.js

echo ""
echo "${bold}[INSTALLING]${normal}"
echo "${bold}[Installing base]${normal}"
sudo /tmp/ddremove.sh
echo "${bold}[Installing loose files]${normal}"
sudo mv /tmp/lighttheme/pvemanagerlib.js /usr/share/pve-manager/js/pvemanagerlib.js
sudo mv /tmp/lighttheme/charts.js /usr/share/javascript/extjs/charts.js
sudo mv /tmp/lighttheme/proxmoxlib.js /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js

echo ""
echo "${bold}[CLEANING]${normal}"
echo "${bold}[Cleaning temp files]${normal}"
rm -rf /tmp/lighttheme

echo ""
echo "${bold}[DONE]${normal}"
