#!/bin/bash
bold=$(tput bold)
normal=$(tput sgr0)

echo "${bold}[PATCH CHECK]${normal}"
echo "No patch available"
read -p "Press any key to continue..." -n1 -s
echo ""

echo ""
echo "${bold}[DONE]${normal}"
