#!/bin/bash
bold=$(tput bold)
normal=$(tput sgr0)

echo "${bold}[PRECHECKING]${normal}"
echo "${bold}[Updating apt-cache]${normal}"
sudo apt-get update

echo ""
echo "${bold}[UPDATING]${normal}"
echo "${bold}[Updating SYSTEM]${normal}"
sudo apt-get dist-upgrade
read -p "Press any key to continue..." -n1 -s
echo ""
echo "${bold}[Updating SHELL EXTENSIONS]${normal}"
echo "${bold}[Updating powerlevel10k]${normal}"
git -C ~/.oh-my-zsh/custom/themes/powerlevel10k pull
echo "${bold}[Updating zsh-autosuggestions]${normal}"
git -C ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions pull
echo "${bold}[Updating CONFIGS]${normal}"
echo "${bold}[Updating aria2]${normal}"
mkdir -p ~/.config/aria2
curl https://raw.githubusercontent.com/voltamage/armbian-glusterfs/master/.config/aria2/aria2.conf > ~/.config/aria2/aria2.conf -#
echo "${bold}[Updating neofetch]${normal}"
mkdir -p ~/.config/neofetch
curl https://raw.githubusercontent.com/voltamage/armbian-glusterfs/master/.config/neofetch/config.conf > ~/.config/neofetch/config.conf -#
echo "${bold}[Updating SCRIPTS]${normal}"
echo "${bold}[Updating brsync]${normal}"
curl https://raw.githubusercontent.com/voltamage/armbian-glusterfs/master/scripts/brsync > ~/scripts/brsync -#
sudo chmod u+x ~/scripts/brsync
echo "${bold}[Updating fnd]${normal}"
curl https://raw.githubusercontent.com/voltamage/armbian-glusterfs/master/scripts/fnd > ~/scripts/fnd -#
sudo chmod u+x ~/scripts/fnd
echo "${bold}[Updating maintain]${normal}"
curl https://raw.githubusercontent.com/voltamage/armbian-glusterfs/master/scripts/maintain > ~/scripts/maintain -#
sudo chmod u+x ~/scripts/maintain
echo "${bold}[Updating mfnd]${normal}"
curl https://raw.githubusercontent.com/voltamage/armbian-glusterfs/master/scripts/mfnd > ~/scripts/mfnd -#
sudo chmod u+x ~/scripts/mfnd
echo "${bold}[Updating ALIASES]${normal}"
curl https://raw.githubusercontent.com/voltamage/armbian-glusterfs/master/.oh-my-zsh/custom/aliases.zsh > ~/.oh-my-zsh/custom/aliases.zsh -#
echo "${bold}[Updating PKGLIST]${normal}"
comm -12 <(grep 'sudo apt-get install' ~/.zsh_history | sed '/|/d' | awk '{$1=$2=$3=$4=""; print $0}' | sed s/\\s/\\n/g | sort -n) <(dpkg --list | awk '{print $2}' | sed 's/:armhf//' | sort -n) | sed '/^$/d' > ~/.pkglist

echo ""
echo "${bold}[CLEANING]${normal}"
echo "${bold}[Cleaning orphaned packages]${normal}"
sudo apt-get autoremove --purge
echo "${bold}[Cleaning package caches]${normal}"
sudo apt-get clean
echo "${bold}[Cleaning junk directories]${normal}"
sudo rm -rf /root/.lesshst
sudo rm -rf /root/.wget-hsts
rm -rf ~/.lesshst
rm -rf ~/.wget-hsts
/home/$USER/scripts/rmshit.py

echo ""
echo "${bold}[POSTCHECKING]${normal}"
echo "${bold}[Checking reboot]${normal}"
sudo needrestart

echo ""
echo "${bold}[DONE]${normal}"
exec zsh
