#!/bin/bash
bold=$(tput bold)
normal=$(tput sgr0)

echo "${bold}[UPDATING)]${normal}"
echo "${bold}[Updating SOURCES (Switching to community version)]${normal}"
sudo cp /etc/apt/sources.list.d/pve-enterprise.list /etc/apt/sources.list.d/pve-enterprise.list.bak
sudo mv /etc/apt/sources.list.d/pve-enterprise.list /etc/apt/sources.list.d/pve-community.list
sudo sed -i -e 's/https/http/g' -e 's/enterprise./download./g' -e 's/pve-enterprise/pve-no-subscription/g' /etc/apt/sources.list.d/pve-community.list

echo ""
echo "${bold}[Updating SOURCES (Adding docker)]${normal}"
sudo cp /etc/apt/sources.list /etc/apt/sources.list.bak
sudo apt-get -y install apt-transport-https ca-certificates gnupg2 software-properties-common
curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
sudo sed -i -e '/#/d' -e 's/contrib /contrib non-free/g' -e '/^$/d' /etc/apt/sources.list

echo ""
echo "${bold}[PRECHECKING]${normal}"
echo "${bold}[Updating apt-cache]${normal}"
sudo apt-get update

echo ""
echo "${bold}[UPDATING]${normal}"
echo "${bold}[Updating SYSTEM]${normal}"
sudo apt-get dist-upgrade

echo ""
echo "${bold}[INSTALLING]${normal}"
echo "${bold}[Installing prerequisites]${normal}"
sudo apt-get -y install git zsh
echo "${bold}[Installing oh-my-zsh]${normal}"
yes | sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
sudo chsh --shell /usr/bin/zsh $USER

echo ""
echo "${bold}[REVIEW]${normal}"
echo "${bold}[Review sources]${normal}"
cat /etc/apt/sources.list /etc/apt/sources.list.d/*.list
echo "${bold}[Review shell]${normal}"
awk -F: -v user="$USER" '$1 == user {print $NF}' /etc/passwd

echo ""
echo "${bold}[DONE]${normal}"
zsh
