#!/bin/bash
bold=$(tput bold)
normal=$(tput sgr0)

echo "${bold}[INSTALLING]${normal}"
echo "${bold}[Installing PLUGINS]${normal}"
echo "${bold}[Installing zsh-autosuggestions]${normal}"
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

echo ""
echo "${bold}[CONFIGURING]${normal}"
echo "${bold}[Configuring scripts folder]${normal}"
mkdir ~/scripts
echo "${bold}[Configuring .zshrc]${normal}"
sed -i '/PATH=$HOME/ a export PATH=$HOME/scripts:$PATH' ~/.zshrc
sed -i '/ZSH_THEME="/c\ZSH_THEME="powerlevel10k/powerlevel10k"' ~/.zshrc
sed -i '/DISABLE_UPDATE_PROMPT/c\DISABLE_UPDATE_PROMPT="true"' ~/.zshrc
sed -i '/UPDATE_ZSH_DAYS/c\export UPDATE_ZSH_DAYS=1' ~/.zshrc
sed -i '/plugins=(git)/c\plugins=(git zsh-autosuggestions)' ~/.zshrc

echo ""
echo "${bold}[REVIEW]${normal}"
echo "${bold}[Review script folder]${normal}"
ls ~/ | grep scripts
echo "${bold}[Review .zshrc]${normal}"
cat <(cat ~/.zshrc | sed -e '/#/d' -e '/^$/d')
read -p "Press any key to continue..." -n1 -s
echo ""

echo ""
echo "${bold}[DONE]${normal}"
exec zsh
