#!/bin/bash
bold=$(tput bold)
normal=$(tput sgr0)

echo "${bold}[UPDATING)]${normal}"
echo "${bold}[Updating SOURCES (Switching to community version)]${normal}"
sudo cp /etc/apt/sources.list.d/pve-enterprise.list /etc/apt/sources.list.d/pve-enterprise.list.bak
sudo mv /etc/apt/sources.list.d/pve-enterprise.list /etc/apt/sources.list.d/pve-community.list
sudo sed -i -e 's/https/http/g' -e 's/enterprise./download./g' -e 's/pve-enterprise/pve-no-subscription/g' /etc/apt/sources.list.d/pve-community.list
sudo apt-get update
sudo apt-get dist-upgrade

sudo apt-get -y install apt-transport-https ca-certificates gnupg2 software-properties-common
echo ": sudo apt-get install apt-transport-https ca-certificates gnupg2 software-properties-common" >> ~/.zsh_history
curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=armhf] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
sudo sed -i -e '/deb-src/d' -e '/^$/d' /etc/apt/sources.list
sudo apt-get update
