#!/bin/bash
bold=$(tput bold)
normal=$(tput sgr0)

echo "${bold}[INSTALLING]${normal}"
echo "${bold}[Installing PACKAGES]${normal}"
sudo apt-get -y install aria2 docker-ce docker-ce-cli docker-compose htop intel-microcode iotop mediainfo ncdu needrestart nload ranger sshfs tmux vim
echo ": sudo apt-get install aria2 docker-ce docker-ce-cli docker-compose htop intel-microcode iotop mediainfo ncdu needrestart nload ranger sshfs tmux vim" >> ~/.zsh_history
echo "${bold}[Installing NEOFETCH (no recommends)]${normal}"
sudo apt-get -y install neofetch --no-install-recommends
echo ": sudo apt-get install neofetch" >> ~/.zsh_history

echo ""
echo "${bold}[Updating SYSTEM]${normal}"
sudo apt-get -y dist-upgrade

echo ""
echo "${bold}[Installing SCRIPTS]${normal}"
echo "${bold}[Installing brsync]${normal}"
curl https://raw.githubusercontent.com/voltamage/common/master/scripts/brsync > ~/scripts/brsync -#
sudo chmod u+x ~/scripts/brsync
echo "${bold}[Installing fnd]${normal}"
curl https://raw.githubusercontent.com/voltamage/common/master/scripts/fnd > ~/scripts/fnd -#
sudo chmod u+x ~/scripts/fnd
echo "${bold}[Installing maintain]${normal}"
curl https://raw.githubusercontent.com/voltamage/proxmox/master/scripts/maintain > ~/scripts/maintain -#
sudo chmod u+x ~/scripts/maintain
echo "${bold}[Installing mfnd]${normal}"
curl https://raw.githubusercontent.com/voltamage/common/master/scripts/mfnd > ~/scripts/mfnd -#
sudo chmod u+x ~/scripts/mfnd
echo "${bold}[Installing msrsync]${normal}"
curl https://raw.githubusercontent.com/jbd/msrsync/master/msrsync > ~/scripts/msrsync -#
sudo chmod u+x ~/scripts/msrsync
echo "${bold}[Installing nonag]${normal}"
curl https://raw.githubusercontent.com/voltamage/proxmox/master/scripts/nonag > ~/scripts/nonag -#
sudo chmod u+x ~/scripts/nonag
echo "${bold}[Installing rmshit.py]${normal}"
curl https://raw.githubusercontent.com/lahwaacz/Scripts/master/rmshit.py > ~/scripts/rmshit.py -#
sed -i '/.viminfo/d' ~/scripts/rmshit.py
sudo chmod u+x ~/scripts/rmshit.py
echo "${bold}[Installing ALIASES]${normal}"
curl https://raw.githubusercontent.com/voltamage/proxmox/master/.oh-my-zsh/custom/aliases.zsh > ~/.oh-my-zsh/custom/aliases.zsh -#

echo ""
echo "${bold}[CLEANING]${normal}"
echo "${bold}[Cleaning orphaned packages]${normal}"
sudo apt-get autoremove --purge
echo "${bold}[Cleaning package caches]${normal}"
sudo apt-get clean
echo "${bold}[Cleaning junk directories]${normal}"
sudo rm -rf /root/.lesshst
sudo rm -rf /root/.wget-hsts
rm -rf ~/.lesshst
rm -rf ~/.wget-hsts
/home/$USER/scripts/rmshit.py

echo ""
echo "${bold}[CONFIGURING]${normal}"
echo "${bold}[Configuring SYSTEM]${normal}"
echo "${bold}[Configuring dark theme]${normal}"
sudo cp /usr/share/pve-manager/index.html.tpl /usr/share/pve-manager/index.html.tpl.bak2
mkdir /tmp/darktheme
curl https://raw.githubusercontent.com/Weilbyte/PVEDiscordDark/master/serverside/ddInstall.sh > /tmp/darktheme/ddinstall.sh -#
curl https://raw.githubusercontent.com/Weilbyte/PVEDiscordDark/master/serverside/jsmod/6.0-4.sh > /tmp/darktheme/ddjsmod.sh -#
chmod +x /tmp/darktheme/ddinstall.sh
chmod +x /tmp/darktheme/ddjsmod.sh
sudo /tmp/darktheme/ddinstall.sh
sudo /tmp/darktheme/ddjsmod.sh
rm -rf /tmp/darktheme
echo "${bold}[Configuring nag removal]${normal}"
sudo sed -i.bak "s/data.status !== 'Active'/false/g" /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js
sudo systemctl restart pveproxy.service
echo "${bold}[Configuring hosts]${normal}"
sudo cp /etc/hosts /etc/hosts.bak
cp /etc/hosts /tmp/hosts
curl https://raw.githubusercontent.com/voltamage/notes/master/armbian/tmp/hosts -# >> /tmp/hosts
sudo mv /tmp/hosts /etc/hosts
echo "${bold}[Configuring PACKAGES]${normal}"
echo "${bold}[Configuring aria2]${normal}"
mkdir -p ~/.config/aria2
curl https://raw.githubusercontent.com/voltamage/notes/master/armbian/.config/aria2/aria2.conf > ~/.config/aria2/aria2.conf -#
echo "${bold}[Configuring neofetch]${normal}"
mkdir -p ~/.config/neofetch
curl https://raw.githubusercontent.com/voltamage/notes/master/armbian/.config/neofetch/config.conf > ~/.config/neofetch/config.conf -#
echo "${bold}[Configuring vim]${normal}"
echo "SELECTED_EDITOR="/usr/bin/vim.basic"" > ~/.selected_editor
sudo cp ~/.selected_editor /root
echo "${bold}[Configuring .pkglist]${normal}"
comm -12 <(grep 'sudo apt-get install' ~/.zsh_history | sed '/|/d' | awk '{$1=$2=$3=$4=""; print $0}' | sed s/\\s/\\n/g | sort -n) <(dpkg --list | awk '{print $2}' | sed 's/:armhf//' | sort -n) | sed '/^$/d' > ~/.pkglist

echo ""
echo "${bold}[REVIEW]${normal}"
echo "${bold}[Review sources]${normal}"
cat /etc/apt/sources.list /etc/apt/sources.list.d/*.list
read -p "Press any key to continue..." -n1 -s
echo ""
echo "${bold}[Review /etc/hosts]${normal}"
echo "[Hosts]"
cat /etc/hosts
read -p "Press any key to continue..." -n1 -s
echo ""
echo "${bold}[Review timezone]${normal}"
timedatectl
read -p "Press any key to continue..." -n1 -s
echo ""
echo "${bold}[Review locale]${normal}"
locale -a
read -p "Press any key to continue..." -n1 -s
echo ""
echo "${bold}[Review fstab]${normal}"
cat /etc/fstab
read -p "Press any key to continue..." -n1 -s
echo ""
echo "${bold}[Review mounts]${normal}"
cat <(echo "[Mounts]") <(lsblk) <(echo "") <(echo "[Usage]") <(df -h) | less
read -p "Press any key to continue..." -n1 -s
echo ""
echo "${bold}[Review docker service]${normal}"
systemctl --type=service | grep docker
read -p "Press any key to continue..." -n1 -s
echo ""
echo "${bold}[Review aria2]${normal}"
cat ~/.config/aria2/aria2.conf
read -p "Press any key to continue..." -n1 -s
echo ""
echo "${bold}[Review neofetch]${normal}"
neofetch
read -p "Press any key to continue..." -n1 -s
echo ""
echo "${bold}[Review vim]${normal}"
echo "[Root]"
sudo cat /root/.selected_editor
echo "[User]"
cat ~/.selected_editor
read -p "Press any key to continue..." -n1 -s
echo ""
echo "${bold}[Review .zshrc]${normal}"
cat <(cat ~/.zshrc | sed -e '/#/d' -e '/^$/d')
read -p "Press any key to continue..." -n1 -s
echo ""
echo "${bold}[Review aliases]${normal}"
cat ~/.oh-my-zsh/custom/aliases.zsh

echo ""
echo "${bold}[Review .pkglist]${normal}"
read -p "Press any key to continue..." -n1 -s
echo ""
less ~/.pkglist
echo "${bold}[Review filesystem]${normal}"
read -p "Press any key to continue..." -n1 -s
echo ""
cat <(echo "[user folder]") <(ls -la ~/) <(echo "") <(echo "[scripts folder]") <(ls -la ~/scripts) <(echo "") <(echo "[root folder]") <(sudo ls -la /root) <(echo "") <(echo "[tmp folder]") <(ls -la /tmp) <(echo "") | less
echo "${bold}[Review zpool]${normal}"
read -p "Press any key to continue..." -n1 -s
echo ""
cat <(echo "[Status]") <(sudo zpool status) <(echo "") <(echo "[List]") <(sudo zpool list) <(echo "") <(echo "[IOstat]") <(sudo zpool iostat) | less

echo ""
echo "${bold}[POSTCHECKING]${normal}"
echo "${bold}[Checking reboot]${normal}"
sudo needrestart

echo ""
echo "${bold}[DONE]${normal}"
exec zsh
